
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x7f\xebV\x83l:\ne\x9b\xb4\x03\xdd\xe8\xf1\xa6m'
    
_lr_action_items = {'NL':([0,2,8,9,10,11,21,23,24,25,29,30,31,],[2,2,-11,-9,-7,2,-11,-5,-13,-10,-6,-14,-12,]),'NAME':([0,1,2,4,5,6,13,14,16,17,19,20,],[-16,-18,-16,8,-19,-17,21,21,21,21,8,21,]),'INT':([0,1,2,4,5,6,13,14,16,17,19,20,],[-16,-18,-16,9,-19,-17,9,9,9,9,9,9,]),'ADD':([8,9,10,21,22,23,24,25,29,30,31,],[-11,-9,17,-11,17,17,-13,-10,17,-14,-12,]),'SUB':([0,1,2,4,5,6,13,14,16,17,19,20,],[-16,-18,-16,16,-19,-17,16,16,16,16,16,16,]),'LPAREN':([0,1,2,4,5,6,8,9,10,13,14,16,17,19,20,21,22,23,24,25,29,30,31,],[-16,-18,-16,13,-19,-17,-11,-9,18,13,13,13,13,13,13,-11,18,18,18,18,18,-14,-12,]),'PRINT':([0,1,2,4,5,6,19,],[-16,-18,-16,14,-19,-17,14,]),'RPAREN':([9,18,21,22,24,25,26,27,30,31,],[-9,-16,-11,30,-13,-10,31,-15,-14,-12,]),'EQ':([8,12,],[-8,20,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,15,19,21,23,24,25,28,29,30,31,],[-16,-18,-16,0,-16,-19,-17,-1,-11,-9,-7,-3,-4,-16,-11,-5,-13,-10,-2,-6,-14,-12,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmt_list':([4,19,],[7,28,]),'nls':([0,2,11,],[1,1,19,]),'expr':([4,13,14,16,17,19,20,],[10,22,23,24,25,10,29,]),'args':([18,],[26,]),'module':([0,],[3,]),'assignee':([4,19,],[12,12,]),'mnls':([0,2,],[4,6,]),'stmt':([4,19,],[11,11,]),'empty':([0,2,4,18,19,],[5,5,15,27,15,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> mnls stmt_list','module',2,'p_module','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',12),
  ('stmt_list -> stmt nls stmt_list','stmt_list',3,'p_stmt_list_multi','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',16),
  ('stmt_list -> stmt','stmt_list',1,'p_stmt_list_single','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',20),
  ('stmt_list -> empty','stmt_list',1,'p_stmt_list_none','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',24),
  ('stmt -> PRINT expr','stmt',2,'p_print','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',28),
  ('stmt -> assignee EQ expr','stmt',3,'p_assign','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',32),
  ('stmt -> expr','stmt',1,'p_discard','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',36),
  ('assignee -> NAME','assignee',1,'p_assignee','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',40),
  ('expr -> INT','expr',1,'p_int','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',44),
  ('expr -> expr ADD expr','expr',3,'p_add','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',48),
  ('expr -> NAME','expr',1,'p_name','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',52),
  ('expr -> expr LPAREN args RPAREN','expr',4,'p_call','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',56),
  ('expr -> SUB expr','expr',2,'p_neg','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',60),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_paren','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',64),
  ('args -> empty','args',1,'p_args_none','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',68),
  ('empty -> <empty>','empty',0,'p_empty','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',72),
  ('nls -> NL mnls','nls',2,'p_nls','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',76),
  ('mnls -> nls','mnls',1,'p_mnls_more','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',80),
  ('mnls -> empty','mnls',1,'p_mnls_none','/home/mvitousek/Dropbox/Work/Colorado/Classes/Compilers/parse.py',84),
]
